services:
  app:
    build: .
    container_name: authshield-app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authshield
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true

    networks:
      - authshield

  postgres:
    image: postgres:16
    container_name: authshield-db
    restart: always
    environment:
      POSTGRES_DB: authshield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authshield"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authshield

  redis:
    image: redis:7
    container_name: authshield-redis
    ports:
      - "6379:6379"
    networks:
      - authshield

volumes:
  postgres_data:

networks:
  authshield:
    driver: bridge